blog/urls.py
from django.urls import path
from .views import Inicio, post_detail, render_posts

app_name= 'blog'

urlpatterns=[
    path("", render_posts, name="post"),
    path("<int:post_id>", post_detail, name="post_detail")
    ]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static
from django.conf import settings
from blog import urls
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include(('blog.urls', 'base'))),
    path('contacto/', include('contacto.urls')),
    path('proyectos/', include('proyectos.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from ckeditor.fields import  RichTextField


# Create your models here.
class ModeloBase(models.Model):
    id=models.AutoField(primary_key=True)
    estado= models.BooleanField('Estado', default=True)
    fecha_creacion=models.DateField('Fecha de Creación', auto_now=False, auto_now_add=True)
    fecha_modificacion=models.DateField('Fecha de Modificación', auto_now=True, auto_now_add=False)
    fecha_eliminacion=models.DateField('Fecha de eliminación', auto_now=True, auto_now_add=False)  


    class Meta:
        abstract= True #la clase abstracta permite no mandar esto a la db, sino que agregarlas donde lo requiramos



class Categoria(ModeloBase):
    nombre= models.CharField('Nombre de la Categoria', max_length=100, unique=True)
    imagen_referencial=models.ImageField('Imagen Referencial', upload_to='categoria/images/')

    class Meta:
        verbose_name= "Categoria"
        verbose_name_plural= "Categorias"

    def __str__(self):
        return self.nombre


class Autor(ModeloBase):
    nombre= models.CharField("Nombres", max_length=100)
    apellidos=models.CharField("Apellidos", max_length=120)
    email=models.EmailField("Correo Electrónico", max_length=150)
    descripcion=models.TextField("Descripción")
    web=models.URLField("Web", null=True, blank=True)
    linkedin=models.URLField("LinkedIn", null=True, blank=True)
    github=models.URLField("GitHub", null=True, blank=True)
    img = models.ImageField('Imagen Referencial', null = True, blank = True,upload_to = 'blog/images/autores/')

    class Meta:
        verbose_name= "Autor"
        verbose_name_plural= "Autores"

    def __str__(self):
        return "{1} {0}".format(self.apellidos,self.nombre)

class Post(ModeloBase):
    titulo=models.CharField("Titulo del Post", max_length=150, unique=True)
    slug=models.CharField("Slug", max_length=150, unique=True)
    descripcion=models.TextField("Descripción")
    autor=models.ForeignKey(Autor, on_delete=models.CASCADE)
    categoria=models.ForeignKey(Categoria,on_delete=models.CASCADE)
    contenido=RichTextField()
    img=models.ImageField("Imagen", upload_to="blog/images/", max_length=255)
    publicado= models.BooleanField("Publicado/No Publicado", default=False)
    fecha_publicacion= models.DateField("Fecha publcación")


    class Meta:
        verbose_name= "Post"
        verbose_name_plural= "Posts"

    def __str__(self):
        return self.titulo



class Web(ModeloBase):
    nosotros=models.TextField("Nosotros")
    email=models.EmailField("Correo Electrónico", max_length=150)

    class Meta:
        verbose_name= "Web"
        verbose_name_plural= "Webs"

    def __str__(self):
        return self.nosotros


class RedesSociales(ModeloBase):
    instagram=models.URLField("Instagram")
    linkedin=models.URLField("LinkedIn", null=True, blank=True)
    stackoverflow=models.URLField("Stackoverflow", null=True, blank=True)


    class Meta:
        verbose_name="Red Social"
        verbose_name_plural="Redes Sociales"

    def __str__(self):
        return self.linkedin

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView

from blog.models import Post
import random
#from .models import Posts
# Create your views here.

class Inicio(ListView):
    def get(self,request,*args, **kwargs):
        posts= list(Post.objects.filter(
            estado= True, 
            publicado= True
            ).values_list("id", flat=True)) #para obtenerlos sin hacerlos tupla
        
        #print("++++++++++++++++++++",posts)
        principal= random.choice(posts)

        principal= Post.objects.get(id= principal)
        

        return render(request, "indexpost.html",{"principal":principal})


def render_posts(request):
    post= Post.objects.all()
    return render(request, 'post.html',{"posts":post})

def post_detail(request, post_id):
    posts=get_object_or_404(Post, pk=post_id)
    return render(request, "post_detail.html", {"post":posts})

blog/templates/index.html
{% extends 'layout.html' %}

{% block content %}
    
<div class="text-center" >
    <h1>{{post.tittle}}</h1>
    <h3 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h3>
    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
</div>
    

<div class="my-4" style="font-size:19px;">
    <p>{{post.description|safe}}</p>
    
</div>

    
    

{% endblock %}

blog/templates/indexpost.html
{% extends 'layout.html' %}

{% block content %}
    

<div class="slide-one-item home-slider owl-carousel">
    <div class="site-cover site-cover-sm same-height overlay" style="background-image: url({{principal.img.url}});">
      <div class="container">
        <div class="row same-height align-items-center">
          <div class="col-md-12 col-lg-6">
            <div class="post-entry">
    
              <span class="post-category text-white bg-success mb-3">{{ principal.categoria | upper }}</span>

              <h2 class="mb-4">{{ principal.titulo }}</h2>
              <div class="post-meta align-items-center text-left">
                
                {% if principal.autor.img %}
                    <figure class="author-figure mb-0 mr-3 float-left"><img src="{{ principal.autor.img.url }}" alt="Image" class="img-fluid"></figure>
                {% endif %}
                    
                
                <span class="d-inline-block mt-1">Autor: {{ principal.autor }}</span>
                <span>{{ principal.fecha_publicacion }}</span>

        
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


{% endblock %}

blog/templates/post.html
{% extends 'layout.html' %}

{% block content %}
    {% for post in posts %}
        <div class="p-3">
            <div class="card card-body bg-black">
                <div class="row">
                    <div class="col-3">
                        <img src="{{post.img.url}}" alt="{{post.titulo}}" class="img-fluid"  style="height: 200px;width: 400px;" >
                    </div>
                    <div class="col-9" style="font-family: Helvetica, Sans-Serif;">
                        <span class="post-category text-white bg-danger mb-3" style="font-family:Times New Roman, Times, serif;">&nbsp;&nbsp;{{ post.categoria | upper }}&nbsp;&nbsp;</span>
                        <h2>{{post.titulo}}</h2> 
                        <p>{{post.descripcion|striptags|truncatechars:100 }}</p>
                        <p>{{post.fecha_publicacion|date:'d M Y'|upper}}</p>
                        <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary" style="background-color: purple; border-color: darkmagenta;">{{post.titulo}}</a> 
                    </div>
                </div>

                <!-- LLAMA A LA APP DEL url.py y la funcion path post_detail recibe el parametro post id-->

            </div>
        </div>
        
    {% endfor %}

    {% endblock %}
        
    

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}
    
<div class="text-center" style="font-family: Helvetica, Sans-Serif;" >
    <h1>{{post.titulo}}</h1>

    <br>
    <img src="{{post.img.url}}" alt="{{post.titulo}}" class="img-fluid">
</div>
<br> <br>

<figure class="author-figure mb-0 mr-3 float-left"><img src="{{ post.autor.img.url }}" alt="Image" class="img-circle" style="height: 50px;width: 50px;border-radius: 35px;"><strong>&nbsp;&nbsp;{{post.autor}}</strong></figure>
<h3 class="my-2 h5 text-muted" style="font-size: 14px;">{{post.fecha_publicacion|date:'F jS Y'}}</h3>
<div class="my-4" style="font-size:19px;" style="font-family: Helvetica, Sans-Serif;">
  
    <p>{{post.descripcion|safe}}</p>
    
</div>
<div class="my-4" style="font-size:19px;">
    <p>{{post.contenido|safe}}</p>
    
</div>
    
    

{% endblock %}