blog/urls.py
from django.urls import path
from .views import Inicio, post_detail, render_posts

app_name= 'blog'

urlpatterns=[
    path("", render_posts, name="post"),
    path("<int:post_id>", post_detail, name="post_detail")
    ]

contacto/urls.py
from django.urls import path

from .views import *

app_name= "contacto"

urlpatterns = [
   
    path('', contacto, name="contacto"),
    
    


]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static
from django.conf import settings
from blog import urls
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include(('blog.urls', 'base'))),
    path('contacto/', include('contacto.urls')),
    path('proyectos/', include('proyectos.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectos/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name= 'proyectos'

urlpatterns=[
    path("", render_posts, name="posts"),
    path("<int:post_id>/", post_detail, name="post_detail")
    ]

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


# Create your models here.

class Project(models.Model):
    tittle=CharField(max_length=100)
    description=CharField(max_length=250)
    image=ImageField(upload_to="portfolio/images/")
    url=URLField(blank=True)

    def __str__(self):
        return self.tittle



class Lenguajes(models.Model):
    tittle=CharField(max_length=25)
    image=ImageField(upload_to="lenguajes/images/")

    def __str__(self):
        return self.tittle



class Databases(models.Model):
    tittle=CharField(max_length=25)
    image=ImageField(upload_to="lenguajes/images/")

    def __str__(self):
        return self.tittle


class Complements(models.Model):
    tittle=CharField(max_length=25)
    image=ImageField(upload_to="lenguajes/images/")

    def __str__(self):
        return self.tittle

portfolio/views.py
from django.shortcuts import render
from .models import Project, Databases, Lenguajes, Complements

# Create your views here.

def home(request):
    proyectos= Project.objects.all()
    lenguajes= Lenguajes.objects.all()
    databases= Databases.objects.all()
    complements= Complements.objects.all()
    
    return render(request, 'home.html',{
    'proyectos': proyectos, 
    'lenguajes':lenguajes , 
    'databases':databases , 
    'complements':complements
    }
    )

portfolio/templates/partials/footer.html
<footer class="footer text-faded text-center py-5">
    <div class="container">
      <p class="m-0">
          <a href="#" class="link">
            <span class="fa-stack fa-lg">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
            </span>
          </a>
          <a href="#" class="link">
            <span class="fa-stack fa-lg">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
            </span>
          </a>
          <a href="#" class="link">
            <span class="fa-stack fa-lg">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
            </span>
          </a>
      </p>
      <p class="m-0 mbt1">&copy; Portafolio Lucas Migliaccio 2022</p>
        <a href="https://github.com/LucasMigliaccio" target="_blank" style="color: darkmagenta;">GitHub</a> ·
        <a href="https://www.linkedin.com/in/lucas-migliaccio-828742196/" target="_blank" style="color: darkmagenta;">LinkedIn</a> ·
        <a href="mailto:lucasmigliaccio10@gmail.com?Subject=Mail%20desde%20el%20portafolio" style="color: darkmagenta;">Mail Directo</a>
      </p>

    </div>
  </footer>

portfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
  <div class="container">
    <a class="navbar-brand fw-medium fst-helvetica" href="/">LM Software</a> <!-- href="/" te lleva al home-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto" >
        
       <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post' %}">Blog</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'proyectos:posts' %}">Proyectos</a>
        </li>

          <a class="nav-link" href="{% url 'contacto:contacto' %}">Contacto</a>
        </li>
        
        <li class="nav-item d-flex align-items-center"> <!-- display flex -->
          <a class="btn btn-primary btn-sm" 
            href="{% static 'portfolio/lucas-migliaccio-cv-ingles.pdf' %}"
            target="_blank"
            style="background-color: purple; border-color: darkmagenta;"
            >Download CV</a><!-- target blank para que abra otra pestaña-->
        </li>
        
      </ul>
    </div>
  </div>
  </nav>