blog/urls.py
from django.urls import path
from .views import Inicio, post_detail, render_posts

app_name= 'blog'

urlpatterns=[
    path("", render_posts, name="post"),
    path("<int:post_id>", post_detail, name="post_detail")
    ]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static
from django.conf import settings
from blog import urls
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include(('blog.urls', 'base'))),
    path('contacto/', include('contacto.urls')),
    path('proyectos/', include('proyectos.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectos/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name= 'proyectos'

urlpatterns=[
    path("", render_posts, name="posts"),
    path("<int:post_id>/", post_detail, name="post_detail")
    ]

proyectos/models.py
from datetime import date
from django.db import models
import datetime


# Create your models here.

class Posts(models.Model):
    tittle=models.CharField(max_length=100)
    description=models.TextField()
    image=models.ImageField(upload_to="proyectos/images")
    date=models.DateField(datetime.date.today)

proyectos/views.py
from django.shortcuts import render, get_object_or_404
from .models import Posts

# Create your views here.



def render_posts(request):
    post= Posts.objects.all()
    return render(request, 'post_proy.html',{"posts":post})

def post_detail(request, post_id):
    posts=get_object_or_404(Posts, pk=post_id)
    return render(request, "post_detail_proy.html", {"post":posts})

proyectos/templates/post_detail_proy.html
{% extends 'layout.html' %}

{% block content %}
    
<div class="text-center" style="font-family: Helvetica, Sans-Serif;">
    <h1>{{post.tittle}}</h1>
    <h3 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h3>
    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
</div>
    

<div class="my-4" style="font-size:19px;font-family: Helvetica, Sans-Serif;">
    <p>{{post.description|safe}}</p>
    
</div>

    
    

{% endblock %}

proyectos/templates/post_proy.html
{% extends 'layout.html' %}

{% block content %}
    {% for post in posts %}
        <div class="p-3">
            <div class="card card-body bg-black">
                <div class="row">
                    <div class="col-3">
                        <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
                    </div>
                    <div class="col-9" style="font-family: Helvetica, Sans-Serif;">
                        <h1>{{post.tittle}}</h1>
                        <p>{{post.description|striptags|truncatechars:100 }}</p>
                        <p>{{post.date|date:'d M Y'|upper}}</p>
                        <a href="{% url 'proyectos:post_detail' post.id %}" class="btn btn-primary" style="background-color: purple; border-color: darkmagenta;">{{post.tittle}}</a> 
                        
                    </div>
                </div>

                <!-- LLAMA A LA APP DEL url.py y la funcion path post_detail recibe el parametro post id-->
                

            </div>
        </div>
        
    {% endfor %}

    
    {% endblock %}
        
    